scheme: http
keycloak-port: 8080
keycloak-host: ${scheme}://localhost:${keycloak-port}

server:
  error:
    include-message: always
  port: 7084
  ssl:
    enabled: false

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
        - iss: ${keycloak-host}
          username-claim: preferred_username
          authorities:
          - path: $.realm_access.roles
          - path: $.resource_access.*.roles
        resourceserver:
          permit-all: 
          - "/actuator/health/readiness"
          - "/actuator/health/liveness"
          - "/v3/api-docs/**"
          - "/swagger-ui/**"
        
logging:
  level:
    org:
      springframework:
        boot: INFO
        security: INFO
        
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
      
springdoc:
  swagger-ui:
    show-extensions: true
    with-credentials: true
    oauth:
      clientId: spring-addons-confidential
      clientSecret: ${keycloak-secret}
      scopeSeparator: " "
      scopes: "openid profile"
      use-basic-authentication-with-access-code-grant: false
      useBasicAuthenticationWithAccessCodeGrant: true
---
scheme: https
keycloak-port: 8443

server:
  ssl:
    enabled: true

spring:
  config:
    activate:
      on-profile: ssl